<?php

class autoasiaua_provider {

    private $link = "https://autoasia.ua/uk/search/?node=1&string={article}";

    public function init() {
        echo 'autoasia.ua provider inited' . PHP_EOL;
    }

    /* return [$product->
                        product_title
                        product_article
                        product_brand
                        price (float)
                        availability (int)]
    */
    public function parse($product):array {
        $out_products = [];
        $url = str_replace('{article}', urlencode($product->article_show), $this->link);
        // $url = str_replace('{article}', $product->article, $this->link);
        echo $url . PHP_EOL;

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $output = curl_exec($ch);
        curl_close($ch);

        // Load HTML into DOMDocument
        $dom = new DOMDocument();
        @$dom->loadHTML($output); // Use @ to suppress warnings generated by invalid HTML
        $xpath = new DOMXPath($dom);

        $elements = $xpath->query("//ul[contains(@class, 'ul_items')]//*[contains(@class, 'block_item')]");
        echo "Found: " . $elements->length . PHP_EOL;
        if($elements->length) {
            // Process the elements
            $find_brand_article = [];
            foreach ($elements as $element) {
                $p = new stdClass();
                $p->product_article = $p->product_title = $p->product_brand = '';
                $p->price = $p->availability = 0;

                $codeElements = $xpath->query(".//*[contains(@class, 'code')]", $element);
                if ($codeElements->length > 0) {
                    $codeElement = $codeElements->item(0);

                    // $product_article = $xpath->query(".//span[contains(@class, 'highlight')]", $codeElement);
                    // if($product_article->length > 0) {
                    //     $product_article = $product_article->item(0);
                    //     $p->product_article = trim($product_article->nodeValue);
                    // }

                    $product_article = $xpath->query(".//u", $codeElement);
                    if($product_article->length > 0) {
                        $product_article = $product_article->item(0);
                        $product_article = str_replace('Артикул:', '', $product_article->nodeValue);
                        $p->product_article = trim($product_article);
                    }

                    $brandElements = $xpath->query('.//strong', $codeElement);
                    if ($brandElements->length > 0) {
                        $brandElement = $brandElements->item(0);
                        $p->product_brand = $brandElement->nodeValue;
                    }
                }

                if(empty($p->product_article)) {
                    continue;
                }

                // article must same as product->article
                $articleKey = $this->prepareArticleKey($p->product_article);
                if ($articleKey != $product->article) {
                    continue;
                }

                $priceElements = $xpath->query(".//*[contains(@class, 'price')]/span", $element);
                if ($priceElements->length > 0) {
                    $priceElement = $priceElements->item(0);
                    $p->price = strip_tags($priceElement->nodeValue);
                    $p->price = str_replace(',', '.', $p->price);
                    $p->price = trim($p->price);
                    $p->availability = 1;
                }
                
                if(empty($p->availability) || empty($p->price)) {
                    continue;
                }

                if(empty($p->product_brand)) {
                    $p->product_brand = 'autoasia';
                }

                $titleElements = $xpath->query('.//div[contains(@class, "title")]/a', $element);
                if ($titleElements->length > 0) {
                    $titleElement = $titleElements->item(0);
                    $p->product_title = trim($titleElement->nodeValue);
                }

                $brand_article = "{$p->product_brand}***{$p->product_article}";
                if (in_array($brand_article, $find_brand_article)) {
                    continue;
                }
                $find_brand_article[] = $brand_article;

                unset($p->availability_text);
                // pp($p);
                $out_products[] = (array) $p;
            }
        }

        // pp($out_products);
        return $out_products;
    }

    

    public function prepareArticleKey($text)
    {
        $text = (string) $text;
        $text = trim($text);
        $text = mb_strtolower($text, "utf-8");
        $ua = array('-', '_', ' ', '`', '~', '!', '@', '#', '$', '%', '^', '&', '"', ',', '\.', '\?', '/', ';', ':', '\'', '[+]', '“', '”'
        );
        $en = array('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''
        );
        for ($i = 0; $i < count($ua); $i++) {
            $text = mb_eregi_replace($ua[$i], $en[$i], $text);
        }
        $text = mb_eregi_replace("[-]{2,}", '-', $text);
        return $text;
    }

}