<?php

class mahina_provider {

    // private $link = "https://mahina.in.ua/catalog/?q={article}&submit=%D0%9D%D0%B0%D0%B9%D1%82%D0%B8&section_depth_1=false&section_id=false";
    private $link = "https://mahina.in.ua/catalog/?q={article}";

    public function init() {
        echo 'Mahina provider inited' . PHP_EOL;
    }

    public function parse($product) {
        $url = str_replace('{article}', urlencode($product->article), $this->link);
        // $url = str_replace('{article}', $product->article, $this->link);
// pp($url);
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $output = curl_exec($ch);
        curl_close($ch);

        // Load HTML into DOMDocument
        $dom = new DOMDocument();
        @$dom->loadHTML($output); // Use @ to suppress warnings generated by invalid HTML
        $xpath = new DOMXPath($dom);

        // Translate CSS selector to XPath and query the DOM
        $elements = $xpath->query("//*[@id='catalog']//*[contains(@class, 'a-product__item')]");

        // Process the elements
        foreach ($elements as $element) {
            // Here you can process each element, for example, get the innerHTML or attributes
            
            echo $dom->saveHTML($element) . PHP_EOL;
            // name = .a-product__info-row a || itemprop="url" title
            .article №: A11-7903010AB
            .a-product__brand-item img alt
            // <meta itemprop="price" content="250">
            // .a-product__counter-txt В наличии 5 || input.quantity data-max

            exit;
        }
exit;
        dd($output);
    }

    public function get_products() {
        $products = [];

        $i_article = 2;
        $i_title = 3;
        $i_brand = 7;
        $i_price = 5;
        $i_availability = 4;
        if (!empty($this->file)) {
            foreach ($this->file as $Key => $Row) {
                if($Key < 7) continue;
                if($Key == 7 || $Key == 8) {
                    // [0] => Марка
                    // [1] => Марка\Модель
                    // [2] => Артикул
                    // [3] => Товар
                    // [4] => Остаток
                    // [5] => Спец 1
                    // [6] => Код. Внутр
                    // [7] => Производитель
                    // [8] => Новый код товара
                    // [9] => Харьков
                    // [10] => Одесса
                    if($Row[2] == 'Артикул' && $Row[3] == 'Товар' && $Row[4] == 'Остаток' && $Row[7] == 'Производитель') {
                        continue;
                    }
                    else {
                        echo 'Check file column structure';
                        exit;
                    }
                }
                // pp($Row);
                $product = new stdClass();
                $product->product_article = $Row[$i_article];
                $product->product_title = $Row[$i_title];
                $product->product_brand = $Row[$i_brand];
                $product->price = $Row[$i_price];
                $product->availability = (int) $Row[$i_availability];
                $products[] = $product;
            }
        }
        return $products;
    }

    /* return $product->
                        product_title
                        product_article
                        product_brand
                        price (float)
                        availability (int)
    */
    public function prepare_product($item) {
        $price = mb_ereg_replace('/\s+/', '', $item->price);
        // $price = mb_ereg_replace(' ', '', $price);
        $item->price = (float) str_replace(',', '.', $price);
        $item->availability = (int) $item->availability;
        return (array) $item;
    }

    public function showRows($spreadsheet, $limit = 50)
    {
        echo('<meta charset="utf-8"><pre>');
        // echo ('<meta charset="utf-8">');
        $i = 0;
        if (!empty($spreadsheet))
        foreach ($spreadsheet as $Key => $Row) {
            echo $Key . ': ';
            if ($Row)
            print_r($Row);
            else
            var_dump($Row);
            $i++;
            if ($limit > 0 && $i > $limit)
            exit;
        }
        exit;
    }

}