<?php

class mahina_provider {

    // private $link = "https://mahina.in.ua/catalog/?q={article}&submit=%D0%9D%D0%B0%D0%B9%D1%82%D0%B8&section_depth_1=false&section_id=false";
    private $link = "https://mahina.in.ua/catalog/?q={article}";

    public function init() {
        echo 'Mahina provider inited' . PHP_EOL;
    }

    public function parse($product):array {
        $out_products = [];
        $url = str_replace('{article}', urlencode($product->article), $this->link);
        // $url = str_replace('{article}', $product->article, $this->link);

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $output = curl_exec($ch);
        curl_close($ch);

        // Load HTML into DOMDocument
        $dom = new DOMDocument();
        @$dom->loadHTML($output); // Use @ to suppress warnings generated by invalid HTML
        $xpath = new DOMXPath($dom);

        // Translate CSS selector to XPath and query the DOM
        $elements = $xpath->query("//*[@id='catalog']//*[contains(@class, 'a-product__item-content')]");
        // echo "Found: " . $elements->length . PHP_EOL;
        if($elements->length) {
            // Process the elements
            $find_brand_article = [];
            foreach ($elements as $element) {
                $p = new stdClass();
                $p->product_article = $p->product_title = $p->product_brand = '';
                $p->price = $p->availability = 0;

                // Find inner text in .a-product__counter-txt
                $counterElements = $xpath->query(".//*[contains(@class, 'a-product__counter-txt')]", $element);
                if ($counterElements->length > 0) {
                    $counterElement = $counterElements->item(0);
                    $p->availability_text = trim($counterElement->nodeValue); // Assuming you want to store this in a new property

                    if (strpos($p->availability_text, 'В наличии') !== false) {
                        // input.quantity data-max
                        $inputElements = $xpath->query(".//input[contains(@class, 'quantity')]", $element);
                        if ($inputElements->length > 0) {
                            $inputElement = $inputElements->item(0);
                            $p->availability = $inputElement->getAttribute('data-max');
                        }
                    }
                }

                $metaElements = $xpath->query(".//meta[@itemprop='price']", $element);
                if ($metaElements->length > 0) {
                    $metaElement = $metaElements->item(0);
                    $p->price = $metaElement->getAttribute('content');
                }

                if(empty($p->availability) || empty($p->price)) {
                    continue;
                }

                // name = .a-product__info-row a || itemprop="url" title
                $aElements = $xpath->query('.//a[@itemprop="url"]', $element);
                if ($aElements->length > 0) {
                    $aElement = $aElements->item(0);
                    $p->product_title = $aElement->getAttribute('title');
                }

                // .a-product__brand-item img alt
                $imgElements = $xpath->query(".//*[contains(@class, 'a-product__brand-item')]//img", $element);
                if ($imgElements->length > 0) {
                    $imgElement = $imgElements->item(0);
                    $p->product_brand = $imgElement->getAttribute('alt');
                }

                // .article №: A11-7903010AB
                $articleElements = $xpath->query(".//*[contains(@class, 'article')]", $element);
                if ($articleElements->length > 0) {
                    $articleElement = $articleElements->item(0);

                    $p->product_article = strip_tags($articleElement->textContent);
                    $p->product_article = str_replace('№:', '', $p->product_article);
                    $p->product_article = str_replace('Аналоги', '', $p->product_article);
                    $p->product_article = trim($p->product_article);
                }

                if (empty($p->product_article) || empty($p->product_brand)) {
                    continue;
                }

                $brand_article = "{$p->product_brand}***{$p->product_article}";
                if (in_array($brand_article, $find_brand_article)) {
                    continue;
                }
                $find_brand_article[] = $brand_article;

                unset($p->availability_text);
                // pp($p);
                $out_products[] = (array) $p;
            }
        }

        // pp($out_products);
        return $out_products;
    }

    /* return $product->
                        product_title
                        product_article
                        product_brand
                        price (float)
                        availability (int)
    */

}