<?php

class mahina_provider {

    // private $link = "https://mahina.in.ua/catalog/?q={article}&submit=%D0%9D%D0%B0%D0%B9%D1%82%D0%B8&section_depth_1=false&section_id=false";
    private $link = "https://mahina.in.ua/ua/search/?query={article}&filters={}";

    public function init() {
        echo 'Mahina provider inited' . PHP_EOL;
    }

    /* return [$product->
                        product_title
                        product_article
                        product_brand
                        price (float)
                        availability (int)]
    */
    public function parse($product):array {
        $out_products = [];
        $url = str_replace('{article}', urlencode($product->article_show), $this->link);
        // $url = str_replace('{article}', $product->article, $this->link);
        echo $url . PHP_EOL;

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $output = curl_exec($ch);
        curl_close($ch);

        // Load HTML into DOMDocument

	    // Prepend UTF-8 meta tag to the HTML
	    $html = '<meta http-equiv="Content-Type" content="text/html; charset=utf-8">' . $output;

	    $dom = new DOMDocument('1.0', 'UTF-8');
	    @$dom->loadHTML($html);

        // $dom = new DOMDocument();
        // @$dom->loadHTML($output); // Use @ to suppress warnings generated by invalid HTML
        $xpath = new DOMXPath($dom);

        // Translate CSS selector to XPath and query the DOM
		$elements = $xpath->query("//*[@id='pagination-container']//div[contains(@class, 'product-card') and not(contains(@class, 'product-card__'))]");
        // echo "Found: " . $elements->length . PHP_EOL;
        if($elements->length) {
            // Process the elements
            $find_brand_article = [];
            foreach ($elements as $element) {
                $p = new stdClass();
                $p->product_article = $p->product_title = $p->product_brand = '';
                $p->price = $p->availability = 0;

                // Find inner text in .site-status__txt
                $counterElements = $xpath->query(".//*[contains(@class, 'site-status__txt')]", $element);
                if ($counterElements->length > 0) {
                    $counterElement = $counterElements->item(0);
                    $p->availability_text = trim($counterElement->nodeValue); // Assuming you want to store this in a new property
                    if (strpos($p->availability_text, 'В наявності') !== false) {
                        $p->availability = 1;
                    }
                }

				$priceElements = $xpath->query(".//*[contains(@class, 'site-price__item')]", $element);
                if ($priceElements->length > 0) {
                    $priceElement = $priceElements->item(0);
                    $p->price = trim($priceElement->nodeValue);
                    $p->price = str_replace('грн', '', $p->price);
                    $p->price = str_replace(' ', '', $p->price);
                    $p->price = str_replace(',', '.', $p->price);
                }

                if(empty($p->availability) || empty($p->price)) {
                    continue;
                }

                // article
                $articleElements = $xpath->query(".//*[contains(@class, 'product-card__vendor-code')]", $element);
                if ($articleElements->length > 0) {
                    $articleElement = $articleElements->item(0);
                    $p->product_article = strip_tags($articleElement->textContent);
                    $p->product_article = trim($p->product_article);
                }

                // article must same as product->article
                $articleKey = $this->prepareArticleKey($p->product_article);
                if($articleKey != $product->article) {
                    continue;
                }

                // name
                $nameElements = $xpath->query(".//a[contains(@class, 'product-card__name')]", $element);
                if ($nameElements->length > 0) {
                    $aElement = $nameElements->item(0);
					$p->product_title = strip_tags($aElement->textContent);
                    $p->product_title = trim($p->product_title);
                }

				// brand
                $brandElements = $xpath->query(".//div[contains(@class, 'product-card__country')]", $element);
                if ($brandElements->length > 0) {
                    $bElement = $brandElements->item(0);
					$p->product_brand = strip_tags($bElement->textContent);
					$p->product_brand = trim(preg_replace('/\s*\(.*?\)\s*/u', '', $p->product_brand)); // видалити текст що в дужках: PREMIUM (Китай)
                }

                if (empty($p->product_article) || empty($p->product_brand)) {
                    continue;
                }

                $brand_article = "{$p->product_brand}***{$p->product_article}";
                if (in_array($brand_article, $find_brand_article)) {
                    continue;
                }
                $find_brand_article[] = $brand_article;

                unset($p->availability_text);
                // pp($p);
                $out_products[] = (array) $p;
            }
        }

        // pp($out_products);
        return $out_products;
    }

    

    public function prepareArticleKey($text)
    {
        $text = (string) $text;
        $text = trim($text);
        $text = mb_strtolower($text, "utf-8");
        $ua = array('-', '_', ' ', '`', '~', '!', '@', '#', '$', '%', '^', '&', '"', ',', '\.', '\?', '/', ';', ':', '\'', '[+]', '“', '”'
        );
        $en = array('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''
        );
        for ($i = 0; $i < count($ua); $i++) {
            $text = mb_eregi_replace($ua[$i], $en[$i], $text);
        }
        $text = mb_eregi_replace("[-]{2,}", '-', $text);
        return $text;
    }

}