<?php

class pandaautocomua_provider {

    private $link = "https://panda-auto.com.ua/ua/search/all_{article}";

    public function init() {
        echo 'panda-auto.com.ua provider inited' . PHP_EOL;
    }

    /* return [$product->
                        product_title
                        product_article
                        product_brand
                        price (float)
                        availability (int)]
    */
    public function parse($product):array {
        $out_products = [];
        $url = str_replace('{article}', urlencode($product->article_show), $this->link);
        // $url = str_replace('{article}', $product->article, $this->link);
        echo $url . PHP_EOL;

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $output = curl_exec($ch);
        curl_close($ch);

        // Load HTML into DOMDocument
        $dom = new DOMDocument();
        @$dom->loadHTML($output); // Use @ to suppress warnings generated by invalid HTML
        $xpath = new DOMXPath($dom);

        $elements = $xpath->query("//*[@id='catalog__rside_products']//*[contains(@class, 'catalog__product-main')]/div");
        echo "Found: " . $elements->length . PHP_EOL;
        if($elements->length) {
            // Process the elements
            $find_brand_article = [];
            foreach ($elements as $element) {
                $p = new stdClass();
                $p->product_article = $p->product_title = $p->product_brand = '';
                $p->price = $p->availability = 0;

                $p->product_article = $element->getAttribute('data-code');

                // article must same as product->article
                $articleKey = $this->prepareArticleKey($p->product_article);
                if ($articleKey != $product->article) {
                    continue;
                }

                $counterElements = $xpath->query(".//*[contains(@class, 'product__status')]/span", $element);
                if ($counterElements->length > 0) {
                    $counterElement = $counterElements->item(0);
                    $p->availability_text = trim($counterElement->nodeValue);
                    if ($p->availability_text == 'В наявності') {
                        $p->availability = 1;
                    }
                }

                $priceElements = $xpath->query(".//*[contains(@class, 'product__prices-numbers')]/strong", $element);
                if ($priceElements->length > 0) {
                    $priceElement = $priceElements->item(0);
                    $p->price = strip_tags($priceElement->nodeValue);
                    $p->price = str_replace('₴', '', $p->price);
                    $p->price = trim($p->price);
                }
                
                if(empty($p->availability) || empty($p->price)) {
                    continue;
                }

                $brandElements = $xpath->query('.//img[contains(@class, "product__logo--img")]', $element);
                if ($brandElements->length > 0) {
                    $brandElement = $brandElements->item(0);
                    $p->product_brand = $brandElement->getAttribute('title');
                }

                if(empty($p->product_brand)) {
                    $p->product_brand = 'panda-auto';
                }

                $titleElements = $xpath->query('.//div[contains(@class, "product__title")]/a', $element);
                if ($titleElements->length > 0) {
                    $titleElement = $titleElements->item(0);
                    $p->product_title = trim($titleElement->nodeValue);
                }

                $brand_article = "{$p->product_brand}***{$p->product_article}";
                if (in_array($brand_article, $find_brand_article)) {
                    continue;
                }
                $find_brand_article[] = $brand_article;

                unset($p->availability_text);
                // pp($p);
                $out_products[] = (array) $p;
            }
        }

        // pp($out_products);
        return $out_products;
    }

    

    public function prepareArticleKey($text)
    {
        $text = (string) $text;
        $text = trim($text);
        $text = mb_strtolower($text, "utf-8");
        $ua = array('-', '_', ' ', '`', '~', '!', '@', '#', '$', '%', '^', '&', '"', ',', '\.', '\?', '/', ';', ':', '\'', '[+]', '“', '”'
        );
        $en = array('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''
        );
        for ($i = 0; $i < count($ua); $i++) {
            $text = mb_eregi_replace($ua[$i], $en[$i], $text);
        }
        $text = mb_eregi_replace("[-]{2,}", '-', $text);
        return $text;
    }

}