<?php

class vostokpartsua_provider {

    private $link = "https://vostok-parts.ua/catalog/sub/search/?text={article}";

    public function init() {
        echo 'vostok-parts.ua provider inited' . PHP_EOL;
    }

    /* return [$product->
                        product_title
                        product_article
                        product_brand
                        price (float)
                        availability (int)]
    */
    public function parse($product):array {
        $out_products = [];
        $url = str_replace('{article}', urlencode($product->article_show), $this->link);
        // $url = str_replace('{article}', $product->article, $this->link);
        echo $url . PHP_EOL;

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $output = curl_exec($ch);
        curl_close($ch);

        // Load HTML into DOMDocument
        $dom = new DOMDocument();
        @$dom->loadHTML($output); // Use @ to suppress warnings generated by invalid HTML
        $xpath = new DOMXPath($dom);

        // Translate CSS selector to XPath and query the DOM
        $elements = $xpath->query("//*[@id='content']//*[contains(@class, 'item')]");
        echo "Found: " . $elements->length . PHP_EOL;
        if($elements->length) {
            // Process the elements
            $find_brand_article = [];
            foreach ($elements as $element) {
                $p = new stdClass();
                $p->product_article = $p->product_title = $p->product_brand = '';
                $p->price = $p->availability = 0;

                // Find inner text in .availability
                $counterElements = $xpath->query(".//*[contains(@class, 'availability')]", $element);
                if ($counterElements->length > 0) {
                    $counterElement = $counterElements->item(0);
                    $p->availability_text = trim($counterElement->nodeValue);
                    if ($p->availability_text == 'В наявності') {
                        $p->availability = 1;
                    }
                }
                
                // Find inner text in .price > span
                $priceElements = $xpath->query(".//*[contains(@class, 'price')]/span", $element);
                if ($priceElements->length > 0) {
                    $priceElement = $priceElements->item(0);
                    $p->price = trim($priceElement->nodeValue);
                }

                if(empty($p->availability) || empty($p->price)) {
                    continue;
                }

                // .articul Артикул: 1014001708-BER
                $articleElements = $xpath->query(".//*[contains(@class, 'articul')]", $element);
                if ($articleElements->length > 0) {
                    $articleElement = $articleElements->item(0);

                    $p->product_article = strip_tags($articleElement->textContent);
                    $p->product_article = str_replace('Артикул:', '', $p->product_article);
                    $p->product_article = trim($p->product_article);
                }
                
                // article must same as product->article
                $articleKey = $this->prepareArticleKey($p->product_article);
                if($articleKey != $product->article) {
                    continue;
                }

                $nameElements = $xpath->query(".//*[contains(@class, 'name')]/a", $element);
                if ($nameElements->length > 0) {
                    $nameElement = $nameElements->item(0);
                    $p->product_title = strip_tags($nameElement->textContent);
                }

                // .a-product__brand-item img alt
                // $imgElements = $xpath->query(".//*[contains(@class, 'a-product__brand-item')]//img", $element);
                // if ($imgElements->length > 0) {
                //     $imgElement = $imgElements->item(0);
                //     $p->product_brand = $imgElement->getAttribute('alt');
                // }

                $p->product_brand = 'vostok';
                if (empty($p->product_article) || empty($p->product_brand)) {
                    continue;
                }

                $brand_article = "{$p->product_brand}***{$p->product_article}";
                if (in_array($brand_article, $find_brand_article)) {
                    continue;
                }
                $find_brand_article[] = $brand_article;

                unset($p->availability_text);
                // pp($p);
                $out_products[] = (array) $p;
            }
        }

        // pp($out_products);
        return $out_products;
    }

    

    public function prepareArticleKey($text)
    {
        $text = (string) $text;
        $text = trim($text);
        $text = mb_strtolower($text, "utf-8");
        $ua = array('-', '_', ' ', '`', '~', '!', '@', '#', '$', '%', '^', '&', '"', ',', '\.', '\?', '/', ';', ':', '\'', '[+]', '“', '”'
        );
        $en = array('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''
        );
        for ($i = 0; $i < count($ua); $i++) {
            $text = mb_eregi_replace($ua[$i], $en[$i], $text);
        }
        $text = mb_eregi_replace("[-]{2,}", '-', $text);
        return $text;
    }

}